a <- matrix(1:20, nrow=5, ncol=4, byrow=TRUE)
print(a)
b <- matrix(1:9, nrow=3, byrow=TRUE, dimnames=list(c("A", "B", "C"), c("X", "Y", "Z")))
print(b)
c <- matrix(1:4, nrow=2, byrow=FALSE, dimnames=list(c("Row1", "Row2"), c("Col1", "Col2")))
print(c)
